import {createView,DISTRICTS} from './view.js';
import {newRun,resumeRun,unpackState,step,DT,score,encodeInput,decodeInput,LABELS,botInput} from './physics.js';
import {validateRecord,DEFAULTS} from './service.js';
const $=id=>document.getElementById(id),keys=new Set(),touch={x:0,z:0,jump:false};let jumpPressed=false,phase='menu',settings={...DEFAULTS},day=new Date().toISOString().slice(0,10),towerId='',bridge=null,context=null,run=newRun(day),job=null,record={bestFloor:0,bestScore:0,totalTime:0,runs:0,milestones:{}},accumulator=0,lifeStarted=0,toastUntil=0,invoice=null,invoiceTimer=null,qrApp=null,invoiceGeneration=0,modalFocus=null;
let view;try{view=createView($('view'));}catch(e){$('fatal').hidden=false;$('fatal').textContent='This game needs WebGL. Enable hardware acceleration or try another browser.';throw e;}
function setPhase(p){phase=p;for(const id of ['menu','result','pause'])$(id).hidden=id!==p;$('hud').hidden=p==='menu';$('course').hidden=p==='menu';$('game').classList.toggle('playing',p==='playing');$('game').classList.toggle('in-menu',p==='menu');$('mode').textContent=job?.eligible?'DAILY RUN':'FREE PRACTICE';}
function toast(text){$('toast').textContent=text;toastUntil=performance.now()+2400;}
function fmt(seconds,precise=false){const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+(precise?'.'+String(Math.floor(seconds*100)%100).padStart(2,'0'):'');}
let audio=null,audioEnabled=true;
function unlock(){if(!audio)try{audio=new(window.AudioContext||window.webkitAudioContext)();}catch{}audio?.resume();}
function tone(f=.0,d=.12,type='sine',gain=.035,delay=0){if(!audio||!audioEnabled)return;const t=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.001,t);g.gain.linearRampToValueAtTime(gain,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+d);}
function sound(event){if(event==='jump')tone(410,.09,'triangle');else if(event==='land')tone(120,.065,'sine',.025);else if(event==='floor')tone(620,.08);else if(event==='death'){tone(170,.24,'sawtooth',.025);tone(90,.3,'sine',.04,.12);}else if(event==='checkpoint'){[520,650,780,1040].forEach((n,i)=>tone(n,.18,'sine',.04,i*.08));}else if(event==='bounce'||event==='extra-life'||event==='flight')tone(850,.15,'triangle');}
async function api(path,body,method=body?'POST':'GET'){if(!bridge)throw Error('LNbits connection unavailable.');const r=await bridge.request('api',{path:'/api/v1/ext/satrun'+path,method,...(body?{body}:{})});if(!r?.ok)throw Error(r?.error||'LNbits action failed.');return r.data;}
function mergeRecord(other){const r=validateRecord(other);record.bestFloor=Math.max(record.bestFloor,r.bestFloor);record.bestScore=Math.max(record.bestScore,r.bestScore);record.totalTime=Math.max(record.totalTime,r.totalTime);record.runs=Math.max(record.runs,r.runs);for(const [k,t]of Object.entries(r.milestones))record.milestones[k]=Math.min(record.milestones[k]??Infinity,t);}
async function saveRecords(){try{localStorage.setItem('satrun.record',JSON.stringify(record));}catch{}bridge?.request('storage.session.set',{key:'record',value:JSON.stringify(record)}).catch(()=>{});if(context?.public===false)api('/record',{record}).catch(()=>{});}
async function init(){try{try{const r=localStorage.getItem('satrun.record');if(r)mergeRecord(JSON.parse(r));}catch{}bridge=await window.satBridge();context=await bridge.request('context');towerId=context.routeParams?.towerId||context.query?.towerId||'';const info=await api('/info');day=info.day;run=newRun(day,settings);if(towerId){const info=await api('/tower',{towerId});settings=info.settings;}const stored=await bridge.request('storage.session.get',{key:'record'});if(stored.value)mergeRecord(JSON.parse(stored.value));if(context.public===false){const saved=await api('/record');mergeRecord(saved.record);}$('connection').textContent=towerId?'Daily leaderboard ready. One life. Collect extra lives or pay to resume a checkpoint.':'Free practice · one life. Open an operator’s tower link for daily rankings.';}catch(e){$('connection').textContent='Free practice is ready. LNbits rankings and payments are offline.';}finally{if(context?.query?.test==='1')installDiagnostics();$('daily').textContent='DAILY CIRCUIT / '+day+' · 00:00 UTC';updateHud();}}
async function start(fromFloor=0,resumeHandle=null){unlock();closeInvoice();closeModal('board');closeModal('records');keys.clear();touch.x=touch.z=0;touch.jump=false;jumpPressed=false;$('start').disabled=true;let handle=resumeHandle;if(!fromFloor&&towerId){try{handle=await api('/run/start',{towerId,name:$('name').value.trim()||'runner'});day=handle.day;settings=handle.settings;}catch(e){$('connection').textContent='Circuit unavailable · '+e.message+' Try again.';toast('Could not start the run. Try again.');setPhase('menu');$('start').disabled=false;return;}}
 if(handle){settings=handle.settings;day=handle.day;}run=handle?.state?unpackState(handle.state):fromFloor?resumeRun(run):newRun(handle?.seed||day,settings);run.lives=handle?.lives??run.lives;lifeStarted=run.elapsed;job=handle?{handle,reports:[],inflight:null,eligible:true,error:'',done:false}:null;accumulator=0;view.draw(run,.016,true);setPhase('playing');$('start').disabled=false;$('view').focus();tone(440,.12);tone(660,.15,'sine',.035,.1);updateHud();}
function runReport(s){return{event:s.dead?'death':'checkpoint',floor:s.highest,elapsed:s.elapsed,highestTime:s.highestTime,collected:[...s.collected]};}
async function pump(j){if(!j||j.inflight||j.error||!j.reports.length)return j?.inflight;const report=j.reports.shift();j.inflight=(async()=>{try{for(let attempt=0;;attempt++){try{const result=await api('/run/verify',{runId:j.handle.runId,token:j.handle.token,...report});j.handle.runId=result.runId;j.verified=result;break;}catch(e){j.retryable=/unexpected error|too many clients|timeout|timed out|connection|network|fetch|unavailable/i.test(e.message);if(!j.retryable||attempt>=2){j.reports.unshift(report);j.error=e.message;break;}await new Promise(resolve=>setTimeout(resolve,1000*(attempt+1)));}}}finally{j.inflight=null;}})();return j.inflight;}

async function finishJob(j){if(!j)return;while(!j.error&&(j.reports.length||j.inflight)){if(j.inflight)await j.inflight;else await pump(j);}j.done=true;if(j===job)updateContinue();if(j.error){if(j===job)$('ranking-status').textContent='Could not prepare checkpoint resume. Try again.';return;}if(!j.eligible){if(j===job)$('ranking-status').textContent='Practice run · excluded from the daily leaderboard.';return;}try{await api('/run/finish',j.handle);if(j===job)$('ranking-status').textContent='';}catch(e){if(j===job)$('ranking-status').textContent='Could not save the daily score.';}}
function end(){const previous=record.bestFloor,newBest=run.highest>previous;record.bestFloor=Math.max(record.bestFloor,run.highest);record.bestScore=Math.max(record.bestScore,score(run));record.totalTime+=Math.floor(run.elapsed-lifeStarted);record.runs++;for(const [f,t]of Object.entries(run.milestones))record.milestones[f]=Math.min(record.milestones[f]??Infinity,t);saveRecords();setPhase('result');$('reason').textContent=run.reason;$('result-floor').textContent=run.highest;$('new-best').hidden=!newBest;$('result-stats').textContent=fmt(run.elapsed)+' · '+Math.floor(run.height)+' M · '+score(run).toLocaleString()+' POINTS';$('ranking-status').textContent='';if(job)job.reports.push(runReport(run));updateContinue();$('restart').focus();if(newBest){tone(780,.18);tone(1040,.2,'sine',.04,.12);}finishJob(job);}
function updateHud(){$('floor').textContent=String(run.highest).padStart(2,'0');$('best').textContent=record.bestFloor;$('time').textContent=fmt(run.elapsed)+(run.flyUntil>run.t?' · FLY '+Math.ceil(run.flyUntil-run.t)+'s':'');$('lives').textContent=run.lives;const district=DISTRICTS[Math.floor(run.highest/3)%DISTRICTS.length];$('district-name').textContent=district.name;$('district-next').textContent='FLOOR '+(Math.floor(run.highest/3)+1)*3+' / '+district.next;$('progress-fill').style.width=((run.lastPad%(run.frequency*4))/(run.frequency*4)*100)+'%';$('progress-label').textContent='NEXT CHECKPOINT / '+(Math.floor(run.highest/run.frequency)+1)*run.frequency;const next=run.pads.get(run.lastPad+1);$('course').textContent=next?LABELS[next.module||next.type]:'';$('warning').hidden=phase!=='playing'||run.p.y-run.lava>6;$('mode').textContent=job?.eligible?'DAILY RUN':'FREE PRACTICE';}
function human(){const x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+touch.x,z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+touch.z;return{...view.movement(x,z),jump:jumpPressed||touch.jump};}
let last=performance.now(),projection=null;
function frame(now){const dt=Math.min(.05,(now-last)/1000);last=now;if(phase==='playing'){accumulator+=dt;while(accumulator>=DT&&!run.dead){const m=encodeInput(human());step(run,decodeInput(m));jumpPressed=false;touch.jump=false;for(const event of run.events){sound(event);view.effect(event,run.p);if(event==='floor'&&run.highest%3===0)toast('ENTERING / '+DISTRICTS[Math.floor(run.highest/3)%DISTRICTS.length].name);else if(event==='floor'&&run.highest%run.frequency!==0)toast('FLOOR '+String(run.highest).padStart(2,'0')+' / KEEP THE SIGNAL ALIVE');if(event==='checkpoint'){if(job)job.reports.push(runReport(run));toast('CHECKPOINT '+run.checkpoint+' / SIGNAL SAVED');}if(event==='extra-life')toast('+1 LIFE / SIGNAL RESTORED');if(event==='flight')toast('FLIGHT / 5 SECONDS · STEER WITH MOVE');}accumulator-=DT;}if(run.dead)end();else pump(job);}
 projection=view.draw(run,dt);run.events=[];updateHud();if(now>toastUntil)$('toast').textContent='';requestAnimationFrame(frame);}
$('start').addEventListener('click',()=>start());$('restart').addEventListener('click',()=>start());$('pause-restart').addEventListener('click',()=>start());$('invoice-restart').addEventListener('click',()=>start());$('resume').addEventListener('click',()=>{setPhase('playing');$('view').focus();});$('home').addEventListener('click',()=>{run=newRun(day,settings);job=null;setPhase('menu');view.draw(run,.016,true);$('start').focus();});
function pause(){if(phase==='playing'){if(job)job.eligible=false;keys.clear();setPhase('pause');$('resume').focus();}}
addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(!$('invoice').hidden)closeInvoice();else if(!$('board').hidden)closeModal('board');else if(!$('records').hidden)closeModal('records');else if(phase==='pause')$('resume').click();else pause();return;}if(e.code==='KeyC'){view.orbit.reset();toast('CAMERA RESET');}if(e.code==='KeyR'&&phase==='result')start();if(e.code==='Space'&&!e.repeat)jumpPressed=true;keys.add(e.code);});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
let drag=null;$('view').addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};$('view').setPointerCapture(e.pointerId);$('view').focus();});$('view').addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;view.orbit.yaw-=(e.clientX-drag.x)*.005;view.orbit.pitch=Math.max(.3,Math.min(1.2,view.orbit.pitch+(e.clientY-drag.y)*.004));drag.x=e.clientX;drag.y=e.clientY;});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('view').addEventListener(event,()=>drag=null);$('view').addEventListener('contextmenu',e=>e.preventDefault());$('view').addEventListener('wheel',e=>{e.preventDefault();view.orbit.distance=Math.max(10,Math.min(23,view.orbit.distance+e.deltaY*.012));},{passive:false});
$('sound').addEventListener('click',()=>{unlock();audioEnabled=!audioEnabled;$('sound').textContent=audioEnabled?'SOUND ON':'SOUND OFF';$('sound').setAttribute('aria-pressed',String(audioEnabled));});$('fullscreen').hidden=!document.fullscreenEnabled;$('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('game').requestFullscreen();}catch{toast('Fullscreen unavailable.');}});
function openModal(id){modalFocus=document.activeElement;$(id).hidden=false;$(id).querySelector('button')?.focus();}function closeModal(id){if($(id).hidden)return;$(id).hidden=true;modalFocus?.focus();}
for(const modal of document.querySelectorAll('.dialog'))modal.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const nodes=[...modal.querySelectorAll('button:not([disabled]),a[href],input')].filter(n=>!n.hidden),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
async function leaderboard(){openModal('board');$('board-rows').replaceChildren();$('board-status').textContent='Loading verified runs…';try{if(!towerId)throw Error('Open an operator’s tower link to use its daily leaderboard.');const data=await api('/leaderboard',{towerId});data.rows.forEach((r,i)=>{const tr=document.createElement('tr');for(const text of [i+1,r.name,r.floor,fmt(r.timeMs/1000,true)]){const td=document.createElement('td');td.textContent=text;tr.append(td);}$('board-rows').append(tr);});$('board-status').textContent=data.rows.length?'Verified movement replays · cumulative checkpoint runs.':'No verified runs yet. Set the first mark.';}catch(e){$('board-status').textContent=e.message;}}
$('leaderboard-open').addEventListener('click',leaderboard);$('board-refresh').addEventListener('click',leaderboard);$('leaderboard-close').addEventListener('click',()=>closeModal('board'));
$('records-open').addEventListener('click',()=>{openModal('records');$('record-summary').textContent='BEST FLOOR '+record.bestFloor+' · '+record.runs+' RUNS · '+fmt(record.totalTime)+' TOTAL';$('milestones').replaceChildren();for(const [floor,time]of Object.entries(record.milestones).slice(-10)){const p=document.createElement('p');p.textContent='FLOOR '+floor+' / '+fmt(time,true);$('milestones').append(p);}});$('records-close').addEventListener('click',()=>closeModal('records'));
function updateContinue(){$('retry-verification').hidden=!job?.error||!job.retryable;const free=run.lives>0,ready=!job||job.done||job.error;$('continue').hidden=!(run.checkpoint>0&&ready&&(free||settings.continueEnabled&&job?.done&&!job.error));$('continue').textContent=free?'RESUME FLOOR '+run.checkpoint+' · EXTRA LIFE ('+run.lives+' LEFT)':'⚡ RESUME FLOOR '+run.checkpoint+' · '+settings.continuePrice+' SATS';}
async function resumeCheckpoint(paymentHash){const floor=run.checkpoint;let handle=null;if(job&&!job.error){handle=await api('/run/start',{resume:true,runId:job.handle.runId,token:job.handle.token,...(paymentHash?{paymentHash}:{})});}else if(paymentHash){throw Error('Verified checkpoint is unavailable.');}await start(floor,handle);toast('CHECKPOINT '+floor+' / '+run.lives+' LIVES LEFT');sound('checkpoint');}
async function openInvoice(){if(!job?.done||job.error)return;const generation=++invoiceGeneration;$('continue').disabled=true;try{const data=await api('/continue',job.handle);if(generation!==invoiceGeneration)return;invoice=data;openModal('invoice');$('invoice-note').textContent='Resume floor '+data.checkpoint+' · '+data.amount+' sats. Your cumulative run remains eligible for daily rankings.';$('bolt11').value=data.paymentRequest;$('wallet-open').href='lightning:'+data.paymentRequest;$('invoice-status').textContent='Waiting for payment';qrApp=Vue.createApp({render:()=>Vue.h(QrcodeVue.default,{value:'lightning:'+data.paymentRequest.toUpperCase(),size:220,margin:3,level:'M',renderAs:'canvas'})});qrApp.mount($('qr'));invoiceTimer=setInterval(checkInvoice,1800);}catch(e){toast(e.message);}finally{$('continue').disabled=false;}}
async function checkInvoice(){const current=invoice;if(!current)return;try{const status=await api('/continue/status',{paymentHash:current.paymentHash});if(current!==invoice)return;if(status.paid&&status.towerId===current.towerId&&status.checkpoint===current.checkpoint){await resumeCheckpoint(current.paymentHash);}}catch(e){$('invoice-status').textContent='Rechecking payment…';}}
function closeInvoice(){invoiceGeneration++;clearInterval(invoiceTimer);invoiceTimer=null;invoice=null;qrApp?.unmount();qrApp=null;$('qr').replaceChildren();closeModal('invoice');}
$('retry-verification').addEventListener('click',async()=>{if(!job?.error)return;job.error='';job.done=false;$('ranking-status').textContent='';updateContinue();await finishJob(job);});
$('continue').addEventListener('click',async()=>{if(run.lives===0){await openInvoice();return;}$('continue').disabled=true;try{await resumeCheckpoint();}catch(e){toast(e.message);}finally{$('continue').disabled=false;}});$('invoice-close').addEventListener('click',closeInvoice);$('copy-invoice').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('bolt11').value);$('invoice-status').textContent='Invoice copied. Waiting for payment.';}catch{$('bolt11').focus();$('bolt11').select();$('invoice-status').textContent='Select and copy the invoice.';}});addEventListener('pagehide',()=>{clearInterval(invoiceTimer);qrApp?.unmount();},{once:true});
$('stick').addEventListener('pointerdown',e=>{e.preventDefault();$('stick').setPointerCapture(e.pointerId);moveStick(e);});function moveStick(e){if(!e.buttons&&e.type==='pointermove')return;const b=$('stick').getBoundingClientRect();touch.x=Math.max(-1,Math.min(1,(e.clientX-b.x-b.width/2)/35));touch.z=Math.max(-1,Math.min(1,(e.clientY-b.y-b.height/2)/35));}$('stick').addEventListener('pointermove',moveStick);for(const e of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(e,()=>{touch.x=touch.z=0;});$('touch-jump').addEventListener('pointerdown',e=>{e.preventDefault();touch.jump=true;unlock();});
// Diagnostics are opt-in and never enable fake positions in ranked runs.
function installDiagnostics(){window.satTest={state:()=>run,input:()=>({...touch}),phase:()=>phase,projection:()=>projection,orbit:()=>({...view.orbit}),movement:(x,z)=>view.movement(x,z),camera(yaw){view.orbit.yaw=yaw;projection=view.draw(run,.016,true);},job:()=>job?{error:job.error,done:job.done,pending:job.reports.length,eligible:job.eligible}:null,bot(seconds){if(job)job.eligible=false;let target=run.lastPad+1;for(let i=0;i<seconds/DT&&!run.dead;i++){target=Math.max(target,run.lastPad+1);const m=encodeInput(botInput(run,run.pads.get(target)));step(run,decodeInput(m));if(job&&run.events.includes('checkpoint'))job.reports.push(runReport(run));}view.draw(run,.016,true);if(run.dead)end();},practicePose(floor){if(job)job.eligible=false;run=newRun(day,settings,floor);run.checkpoint=Math.floor(floor/run.frequency)*run.frequency;view.draw(run,.016,true);},die(){run.p.y=run.lava-1;step(run);if(job)job.eligible=false;end();}};}
if(new URL(location.href).searchParams.get('test')==='1')installDiagnostics();
setPhase('menu');init();requestAnimationFrame(frame);
