import {createRequire} from 'node:module';import {readFileSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire('/home/talvasconcelos/Work/lnbits_pg/'),{chromium}=require('playwright');const root=new URL('../',import.meta.url),instance=JSON.parse(readFileSync(new URL('.instance/instance.json',import.meta.url))),base=instance.base;
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});
try{
 if(!process.argv.includes('--mobile')){
 await page.goto(instance.play+'?test=1',{waitUntil:'networkidle'});const frame=await(await page.waitForSelector('iframe.wasm-extension-frame')).contentFrame();await frame.waitForFunction(()=>window.satTest&&document.getElementById('connection').textContent.includes('ready'),null,{timeout:30000});
 await frame.locator('#game').screenshot({path:new URL('evidence/menu.png',root).pathname});console.log('MENU READY');
 await frame.locator('#name').fill('test_runner');await frame.locator('#start').click();await frame.waitForFunction(()=>window.satTest.phase()==='playing');console.log('START',await frame.evaluate(()=>window.satTest.job()));
 await frame.locator('#view').focus();await page.keyboard.press('Space');await page.keyboard.down('w');await page.waitForTimeout(500);await page.keyboard.up('w');assert((await frame.evaluate(()=>window.satTest.state().p.y))>.3,'Keyboard jump');
 await page.keyboard.down('a');const x=await frame.evaluate(()=>window.satTest.state().p.x);await page.waitForTimeout(350);await page.keyboard.up('a');assert((await frame.evaluate(()=>window.satTest.state().p.x))<x-.2,'A moves left');
 await page.waitForTimeout(1200);console.log('VERIFY',await frame.evaluate(()=>window.satTest.job()));assert.equal((await frame.evaluate(()=>window.satTest.job())).error,'','Live replay fits runtime budget');
 const rect=await frame.locator('#view').boundingBox();await page.mouse.move(rect.x+rect.width*.7,rect.y+rect.height*.5);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.7+100,rect.y+rect.height*.5+25,{steps:6});await page.mouse.up();assert(Math.abs((await frame.evaluate(()=>window.satTest.orbit())).yaw)>.2,'Camera drag');await page.mouse.wheel(0,150);assert((await frame.evaluate(()=>window.satTest.orbit())).distance>16,'Camera zoom');await page.keyboard.press('c');assert.equal((await frame.evaluate(()=>window.satTest.orbit())).yaw,0,'Camera reset');
 await frame.locator('#game').screenshot({path:new URL('evidence/playing.png',root).pathname});await page.keyboard.press('Escape');await frame.locator('#resume').click();assert.equal(await frame.evaluate(()=>window.satTest.phase()),'playing');
 await frame.evaluate(()=>window.satTest.die());await frame.locator('#result').waitFor();await frame.locator('#game').screenshot({path:new URL('evidence/result.png',root).pathname});await frame.locator('#restart').click();assert.equal((await frame.evaluate(()=>window.satTest.state())).highest,0);console.log('CONTROLS PASS');
 await frame.evaluate(()=>window.satTest.practicePose(10));await frame.locator('#game').screenshot({path:new URL('evidence/checkpoint.png',root).pathname});const projection=await frame.evaluate(()=>window.satTest.projection());assert(Math.abs(projection.screen[0])<.8&&Math.abs(projection.screen[1])<.9,'Runner in view');
 await frame.evaluate(()=>window.satTest.die());await frame.locator('#home').click();await frame.locator('#leaderboard-open').click();await frame.locator('#board-status').filter({hasText:/No verified|Verified movement/}).waitFor();await frame.locator('#leaderboard-close').click();await frame.locator('#records-open').click();assert.equal(await frame.locator('#export, #import, input[type=file]').count(),0);await frame.locator('#record-summary').filter({hasText:'BEST FLOOR'}).waitFor();await frame.locator('#records-close').click();await frame.locator('#sound').click();assert.equal(await frame.locator('#sound').getAttribute('aria-pressed'),'false');
 if(await frame.locator('#fullscreen').isVisible()){await frame.locator('#fullscreen').click();await frame.waitForFunction(()=>!!document.fullscreenElement);await frame.locator('#fullscreen').click();}
 console.log('PUBLIC PASS');
 const owner=await browser.newContext({viewport:{width:1440,height:1000}});await owner.addCookies([{name:'cookie_access_token',value:readFileSync(new URL('.instance/api-token',import.meta.url),'utf8'),url:base,httpOnly:true,sameSite:'Lax'}]);const op=await owner.newPage();op.on('pageerror',e=>errors.push(e.message));await op.goto(base+'/ext/satrun',{waitUntil:'networkidle'});const of=await(await op.waitForSelector('iframe.wasm-extension-frame')).contentFrame();await of.getByRole('button',{name:'Save settings'}).waitFor();const saved=op.waitForResponse(r=>r.url().endsWith('/api/v1/ext/satrun/operator')&&r.request().method()==='POST');await of.getByRole('button',{name:'Save settings'}).click();assert.equal((await(await saved).json()).ok,true,'Owner settings persisted through iframe bridge');assert.equal(await of.locator('.bg-red-10').count(),0,'No owner error banner');await of.getByRole('button',{name:'Copy player link'}).click();await of.locator('body').screenshot({path:new URL('evidence/owner.png',root).pathname});await of.getByRole('button',{name:'Play circuit'}).click();await op.waitForURL('**/ext/satrun/me?*');console.log('OWNER PASS');await owner.close();}await context.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto(base+'/ext/satrun/play?test=1',{waitUntil:'networkidle'});const mf=await(await mp.waitForSelector('iframe.wasm-extension-frame')).contentFrame();await mf.waitForFunction(()=>!!window.satTest);await mf.locator('#start').click();await mf.locator('#touch-jump').waitFor();const jumpBox=await mf.locator('#touch-jump').boundingBox(),stickBox=await mf.locator('#stick').boundingBox();assert(stickBox.x<195&&jumpBox.x>195,'Joystick left and Jump right');const inputSession=await mobile.newCDPSession(mp),stickPoint={id:1,x:stickBox.x+stickBox.width/2+25,y:stickBox.y+stickBox.height/2},jumpPoint={id:2,x:jumpBox.x+jumpBox.width/2,y:jumpBox.y+jumpBox.height/2};
 const initial=await mf.evaluate(()=>({...satTest.state().p}));await inputSession.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[stickPoint,jumpPoint]});await mp.waitForTimeout(200);const both=await mf.evaluate(()=>({...satTest.state().p}));assert(both.y>initial.y+.2,'Simultaneous touch jump');assert(both.x>initial.x+.15,'Simultaneous joystick movement');await inputSession.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await mf.evaluate(()=>satTest.input().x),0,'Release clears joystick input');const released=await mf.evaluate(()=>satTest.state().t);await mf.waitForFunction(t=>satTest.state().dead||satTest.state().t-t>.4,released,{timeout:20000});assert(Math.abs((await mf.evaluate(()=>satTest.state().p.vx)))<.2,'Released movement brakes');
 await inputSession.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[stickPoint]});await inputSession.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert.equal(await mf.evaluate(()=>satTest.input().x),0,'Cancel clears joystick input');await mf.locator('#game').screenshot({path:new URL('evidence/mobile.png',root).pathname});
 assert.deepEqual(errors,[]);const report={scope:process.argv.includes('--mobile')?'mobile controls only':'desktop and mobile',browser:'Chromium headless SwiftShader',keyboardMovement:true,jump:true,cameraDragZoomReset:true,runnerFraming:true,instantRestart:true,pause:true,soundToggle:true,personalRecords:true,leaderboardDialog:true,ownerSaveCopyPlay:true,mobileTouchJump:true,mobileSimultaneousMoveJump:true,mobileReleaseCancel:true,errors,limits:'No human playtest, audio listening or physical device performance measurement.'};if(process.argv.includes('--mobile'))for(const key of ['keyboardMovement','jump','cameraDragZoomReset','runnerFraming','instantRestart','pause','soundToggle','personalRecords','leaderboardDialog','ownerSaveCopyPlay'])delete report[key];writeFileSync(new URL(process.argv.includes('--mobile')?'evidence/mobile-results.json':'evidence/browser-results.json',root),JSON.stringify(report,null,2));console.log('PASS BROWSER');
}catch(e){if(!page.isClosed())await page.screenshot({path:new URL('evidence/browser-failure.png',root).pathname}).catch(()=>{});console.log('ERRORS',errors);throw e;}finally{await browser.close();}
