import {createRequire} from 'node:module';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const require=createRequire('/home/talvasconcelos/Work/lnbits_pg/'),{chromium}=require('playwright'),{base}=JSON.parse(readFileSync(new URL('.instance/instance.json',import.meta.url)));
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-unsafe-swiftshader']});try{const page=await browser.newPage({viewport:{width:1050,height:884}});await page.goto(base+'/ext/satrun/play?test=1',{waitUntil:'networkidle'});const frame=await(await page.waitForSelector('iframe.wasm-extension-frame')).contentFrame();await frame.waitForFunction(()=>!!window.satTest);await frame.locator('#start').click();await frame.evaluate(()=>{satTest.practicePose(15);satTest.die();});
assert.equal((await frame.evaluate(()=>satTest.state())).lives,0,'Death consumes initial life');assert.equal(await frame.locator('#continue').isVisible(),false,'Practice cannot pay for a checkpoint');
await frame.locator('#restart').click();assert.equal((await frame.evaluate(()=>satTest.state())).lives,1);assert.equal((await frame.evaluate(()=>satTest.state())).highest,0);
// One earned extra life permits one resume, then no unpaid further resume.
await frame.evaluate(()=>{satTest.practicePose(15);satTest.state().lives=2;satTest.die();});await frame.locator('#continue').waitFor({state:'visible'});assert.match(await frame.locator('#continue').textContent(),/EXTRA LIFE \(1 LEFT\)/);await frame.locator('#game').screenshot({path:new URL('../evidence/checkpoint-lives.png',import.meta.url).pathname});
const boxes=await frame.evaluate(()=>['restart','continue','ranking-status','home'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return{top:r.top,bottom:r.bottom};}));for(let i=1;i<boxes.length;i++)assert(boxes[i].top>=boxes[i-1].bottom,'Result controls and status do not overlap');
await frame.locator('#continue').click();const state=await frame.evaluate(()=>satTest.state());assert.equal(state.lives,1);assert.equal(state.highest,15);assert.equal(state.checkpoint,10);assert.equal(state.lastPad,40);await frame.evaluate(()=>satTest.die());assert.equal(await frame.locator('#continue').isVisible(),false);

for(const [floor,label]of [[2,'balance'],[3,'moving'],[4,'arena'],[5,'gates'],[6,'split'],[7,'launch']]){await frame.evaluate(f=>satTest.practicePose(f),floor);await frame.locator('#game').screenshot({path:new URL('../evidence/layout-'+label+'.png',import.meta.url).pathname});}
console.log('PASS one total life; earned extra life resumes checkpoint once; restart restores one life; results do not overlap.');}finally{await browser.close();}
