// Isolated FakeWallet only: real component, milestone checks, SQLite and invoice-paid delivery.
import {readFileSync,writeFileSync} from 'node:fs';import assert from 'node:assert/strict';import {newRun,unpackState,packState,step,botInput,encodeInput,decodeInput} from './physics.js';
const root=new URL('.instance/',import.meta.url),instance=JSON.parse(readFileSync(new URL('instance.json',root))),base=instance.base,token=readFileSync(new URL('api-token',root),'utf8');assert(base.endsWith(':5022'),'Never run financial fixtures on the shared server');
async function request(path,body,headers={},method=body?'POST':'GET'){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});const v=await r.json();assert(r.ok,JSON.stringify(v));return v;}
async function api(path,body,auth=false){const r=await request('/api/v1/ext/satrun'+path,body,auth?{Authorization:'Bearer '+token}:{});assert(r.ok,r.error);return r.data;}
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),name='verified_'+Date.now().toString(36);let handle=await api('/run/start',{towerId:instance.towerId,name,floor:99999}),s=newRun(handle.seed,handle.settings),segmentStart=Date.now(),reports=0;const start=Date.now();
assert.equal((await request('/api/v1/ext/satrun/run/verify',{...handle,token:'forged',event:'death',floor:0,elapsed:0,highestTime:0,collected:[]})).ok,false);assert.equal((await request('/api/v1/ext/satrun/run/verify',{...handle,event:'checkpoint',floor:9999,elapsed:0,highestTime:0,collected:[]})).ok,false);
let snapshots=1;
async function play(climb){while(!s.dead&&s.t<1800){const checkpoint=s.checkpoint;while(!s.dead&&s.checkpoint===checkpoint&&s.t<1800){const input=climb&&s.highest<10?botInput(s,s.pads.get(s.lastPad+1)):{x:1,z:0,jump:false};step(s,decodeInput(encodeInput(input)));}
 await sleep(Math.max(0,s.t*1000-(Date.now()-segmentStart)-1200));
 const payload={runId:handle.runId,token:handle.token,event:s.dead?'death':'checkpoint',floor:s.highest,elapsed:s.elapsed,highestTime:s.highestTime,collected:[...s.collected]},v=await api('/run/verify',payload);
 assert.equal(v.floor,s.highest);assert.equal(v.checkpoint,s.checkpoint);assert.equal(v.lives,s.lives);assert.equal(v.dead,s.dead);assert(!('proof'in v));assert.equal((await api('/run/verify',payload)).runId,v.runId,'Lost-response retry reuses snapshot');assert.notEqual(v.runId,handle.runId);handle.runId=v.runId;reports++;snapshots++;
}}

await play(true);assert(s.dead&&s.checkpoint>=10);assert.equal((await api('/run/finish',handle)).floor,s.highest);await api('/run/finish',handle);
assert.equal(s.lives,0,'The initial life is consumed on death');
assert.equal((await request('/api/v1/ext/satrun/run/start',{...handle,resume:true,lives:999})).ok,false,'Client cannot invent extra lives');
const invoice=await api('/continue',{...handle,price:1,walletId:'foreign',checkpoint:99999});assert.equal(invoice.amount,21);assert.equal(invoice.checkpoint,10);assert.equal((await api('/continue/status',{paymentHash:invoice.paymentHash})).paid,false);assert.equal((await request('/api/v1/ext/satrun/run/start',{...handle,resume:true,paymentHash:invoice.paymentHash})).ok,false,'Unpaid invoice cannot resume');
writeFileSync(new URL('verified-checkpoint.json',root),JSON.stringify({handle,state:packState(s)}),{mode:0o600});
const auth={Authorization:'Bearer '+token},wallet=await request('/api/v1/wallet',{name:'Sat Run isolated payer'},auth);await request('/users/api/v1/balance',{id:wallet.id,amount:1000},auth,'PUT');await request('/api/v1/payments',{out:true,bolt11:invoice.paymentRequest},{'X-Api-Key':wallet.adminkey});
let receipt;for(let i=0;i<30;i++){await sleep(500);receipt=await api('/continue/status',{paymentHash:invoice.paymentHash});if(receipt.paid)break;}assert(receipt.paid);assert.equal(receipt.checkpoint,10);assert.equal(receipt.towerId,instance.towerId);
const old={...handle,resume:true,paymentHash:invoice.paymentHash};handle=await api('/run/start',old);snapshots++;assert.equal((await api('/run/start',old)).runId,handle.runId);s=unpackState(handle.state);assert.equal(s.lives,1);segmentStart=Date.now()-s.t*1000;await play(false);assert((await api('/run/finish',handle)).accepted,'Paid extra resume ranks');
const board=await api('/leaderboard',{towerId:instance.towerId});assert.equal(board.rows.filter(r=>r.name===name).length,1);assert.equal((await fetch(base+'/api/v1/ext/satrun/operator')).status,401);
writeFileSync(new URL('../evidence/live-results.json',import.meta.url),JSON.stringify({componentMilestoneChecks:true,checkpointAndDeathUploads:true,noMovementUploads:true,snapshots,reports,checkedFloor:s.highest,checkpoint:s.checkpoint,oneTotalLifeConsumedOnDeath:true,cumulativeTimePreserved:true,resumeRetriesIdempotent:true,freeAndPaidResumesRank:true,leaderboardDedup:true,forgedTokenRejected:true,impossibleProgressRejected:true,clientPriceWalletCheckpointIgnored:true,unpaidReceiptDenied:true,paidInvoiceEventReceipt:true,ownerAuthenticationRequired:true,elapsedSeconds:(Date.now()-start)/1000},null,2));console.log('PASS real WASM checkpoint/death checks, sparse requests, retry idempotency, paid resume and rankings.');
