/* Generated by LNbits ExtensionHostAPI codegen. */
/* Do not edit by hand. */

export type MaybePromise<T> = T | Promise<T>

export type CreateInvoicePublicRequest = {
  sourceId: string
  amount: number
  currency: string
  memo?: string
  extra?: Record<string, unknown>
}

export type CreateInvoiceResponse = {
  paymentHash: string
  paymentRequest: string
  checkingId: string
}

export type EmptyRequest = Record<string, never>

export type ListUserWalletsResponse = {
  wallets?: UserWalletSummary[]
}

export type NowResponse = {
  timestamp: number
}

export type RandomIdRequest = {
  prefix: string
}

export type RandomIdResponse = {
  id: string
}

export type StorageAppendPublicRequest = {
  table: string
  sourceId: string
  data?: Record<string, unknown>
}

export type StorageAppendPublicResponse = {
  id: string
}

export type StorageGetRequest = {
  table: string
  id: string
}

export type StorageGetResponse = {
  dataJson?: string | null
}

export type StoragePaginatedResponse = {
  rowsJson?: string
  total?: number
}

export type StoragePublicPaginatedRequest = {
  table: string
  filters?: Record<string, unknown>
  search?: string | null
  searchFields?: string[]
  sortBy?: string | null
  descending?: boolean
  limit?: number
  offset?: number
  sourceId: string
}

export type StorageSetRequest = {
  table: string
  data?: Record<string, unknown>
}

export type StorageSetResponse = {
  ok?: boolean
}

export type UserWalletSummary = {
  id: string
  name: string
  currency?: string | null
}

export const extensionApiMethods = [
  {
    id: "storage.get",
    namespace: "storage",
    sdkName: "get",
    pythonName: "storage_get",
    hostInterface: "host",
    hostName: "storage_get",
    hostJsName: "storageGet",
    requiredPermission: "ext.storage.read",
  },
  {
    id: "storage.set",
    namespace: "storage",
    sdkName: "set",
    pythonName: "storage_set",
    hostInterface: "host",
    hostName: "storage_set",
    hostJsName: "storageSet",
    requiredPermission: "ext.storage.write",
  },
  {
    id: "storage.append_public",
    namespace: "storage",
    sdkName: "appendPublic",
    pythonName: "storage_append_public",
    hostInterface: "host",
    hostName: "storage_append_public",
    hostJsName: "storageAppendPublic",
    requiredPermission: "ext.storage.append_public",
  },
  {
    id: "storage.get_public",
    namespace: "storage",
    sdkName: "getPublic",
    pythonName: "storage_get_public",
    hostInterface: "host",
    hostName: "storage_get_public",
    hostJsName: "storageGetPublic",
    requiredPermission: "ext.storage.read_public",
  },
  {
    id: "storage.get_public_paginated",
    namespace: "storage",
    sdkName: "getPublicPaginated",
    pythonName: "storage_get_public_paginated",
    hostInterface: "host",
    hostName: "storage_get_public_paginated",
    hostJsName: "storageGetPublicPaginated",
    requiredPermission: "ext.storage.read_public",
  },
  {
    id: "wallet.list_user_wallets",
    namespace: "wallet",
    sdkName: "listUserWallets",
    pythonName: "wallet_list_user_wallets",
    hostInterface: "host",
    hostName: "list_user_wallets",
    hostJsName: "listUserWallets",
    requiredPermission: "wallet.list",
  },
  {
    id: "wallet.create_invoice_public",
    namespace: "wallet",
    sdkName: "createInvoicePublic",
    pythonName: "wallet_create_invoice_public",
    hostInterface: "host",
    hostName: "create_invoice_public",
    hostJsName: "createInvoicePublic",
    requiredPermission: "wallet.create_invoice_public",
  },
  {
    id: "system.random_id",
    namespace: "system",
    sdkName: "id",
    pythonName: "system_random_id",
    hostInterface: "host",
    hostName: "random_id",
    hostJsName: "randomId",
    requiredPermission: null,
  },
  {
    id: "system.now",
    namespace: "system",
    sdkName: "now",
    pythonName: "system_now",
    hostInterface: "host",
    hostName: "now",
    hostJsName: "now",
    requiredPermission: null,
  },
] as const

export type ExtensionHost = {
  host: {
    createInvoicePublic(input: CreateInvoicePublicRequest): MaybePromise<CreateInvoiceResponse>
    listUserWallets(): MaybePromise<ListUserWalletsResponse>
    now(): MaybePromise<NowResponse>
    randomId(input: RandomIdRequest): MaybePromise<RandomIdResponse>
    storageAppendPublic(input: StorageAppendPublicRequest): MaybePromise<StorageAppendPublicResponse>
    storageGet(input: StorageGetRequest): MaybePromise<StorageGetResponse>
    storageGetPublic(input: StorageGetRequest): MaybePromise<StorageGetResponse>
    storageGetPublicPaginated(input: StoragePublicPaginatedRequest): MaybePromise<StoragePaginatedResponse>
    storageSet(input: StorageSetRequest): MaybePromise<StorageSetResponse>
  }
}

export type ExtensionSdk = {
  storage: {
    appendPublic(input: StorageAppendPublicRequest): Promise<StorageAppendPublicResponse>
    get(input: StorageGetRequest): Promise<StorageGetResponse>
    getPublic(input: StorageGetRequest): Promise<StorageGetResponse>
    getPublicPaginated(input: StoragePublicPaginatedRequest): Promise<StoragePaginatedResponse>
    set(input: StorageSetRequest): Promise<StorageSetResponse>
  }
  system: {
    id(input: RandomIdRequest): Promise<RandomIdResponse>
    now(): Promise<NowResponse>
  }
  wallet: {
    createInvoicePublic(input: CreateInvoicePublicRequest): Promise<CreateInvoiceResponse>
    listUserWallets(): Promise<ListUserWalletsResponse>
  }
}

export function createExtensionSdk(
  host: ExtensionHost
): ExtensionSdk {
  return {
    storage: {
      async appendPublic(input) {
        return host.host.storageAppendPublic(input)
      },
      async get(input) {
        return host.host.storageGet(input)
      },
      async getPublic(input) {
        return host.host.storageGetPublic(input)
      },
      async getPublicPaginated(input) {
        return host.host.storageGetPublicPaginated(input)
      },
      async set(input) {
        return host.host.storageSet(input)
      },
    },
    system: {
      async id(input) {
        return host.host.randomId(input)
      },
      async now() {
        return host.host.now()
      },
    },
    wallet: {
      async createInvoicePublic(input) {
        return host.host.createInvoicePublic(input)
      },
      async listUserWallets() {
        return host.host.listUserWallets()
      },
    },
  }
}
